apiVersion: v2
name: monat-ecommerce
description: A Helm chart for Monat E-Commerce Microservices Platform
type: application
version: 1.0.0
appVersion: "1.0"

maintainers:
  - name: Monat Team
    email: team@monat.com

keywords:
  - ecommerce
  - microservices
  - spring-boot
  - kafka
  - kubernetes

home: https://github.com/monat/ecommerce
sources:
  - https://github.com/monat/ecommerce

dependencies: []
